### ISSUE TITLE
Is the Chaplin theme compatible with WP 6.1.1?

### ISSUE THREAD

**Issue by jcamp** [andersnoren/chaplin#2]
Latest releases of WP are quite picky with themes. Just checking if Chaplin is compatible with the latest please?

**Comment by andersnoren** [comment]
@jcamp Chaplin doesn't support any of the new Full Site Editing features in more recent versions of WordPress, but it is compatible.

**Comment by jcamp** [comment]
Many thanks - just as I thought. Was hesitant as there are so many changes in WP 6.1.1.

Cheers
Jonathan
